//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 11:49:47 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.example.spring.soap.api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package api.soap.spring.example.com;
